apiVersion: apps/v1 # This specifies the version of the Kubernetes API being used for this deployment. 'apps/v1' is commonly used for deployments.
kind: Deployment # Defines the type of Kubernetes object. In this case, it's a 'Deployment', which is used to manage stateless applications.
metadata:
  name: flask-k8s-app # The name of the deployment, which uniquely identifies it in the Kubernetes cluster.
spec:
  replicas: 2 # Specifies the number of instances of the application to run.
  selector:
    matchLabels:
      app: flask-k8s-app # Selects the pods that match these labels for management under this deployment.
  template:
    metadata:
      labels:
        app: flask-k8s-app # Labels applied to the pods created by this deployment.
    spec:
      containers:
      - name: flask-k8s-app # The name of the container running in each pod.
      image: flask-k8s-app # Specifies the Docker image to use for the container.
      ports:
      - containerPort: 5000 # The port that the container listens on, matching the Flask app's port.